### ISSUE TITLE
not displaying prop values

### ISSUE THREAD

**Issue by mvolkmann** [RedHatter/svelte-devtools#24] opened 2019-12-26 20:08 UTC
I'm using this with a Svelte app that has components with required props.
I know the props are being passed because their values are being rendered.
But svelte-tools displays "None" under "Props" on the right side.
Is there something I need to do beside just selected a component on the left side to see its props on the right side?

**Environment**
 - Chrome 79.0.3945.79 
- Devtools version 1.2.1
- Svelte version 3.16.7

**Comment by RedHatter** [comment] 2019-12-27 03:51
Duplicate of #26

This is caused by the same issue in svelte 3.16. Can't do anything about it until the PR is merged.

**Closed by RedHatter** 2019-12-27 03:51 UTC
